#!/bin/bash
set -e

apt update && apt upgrade -y

mkdir -p /etc/apt/keyrings/

wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /etc/apt/keyrings/grafana.gpg > /dev/null

echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | tee /etc/apt/sources.list.d/grafana.list

apt update
apt install -y grafana

# Ensure the Grafana directories have the correct permissions
mkdir -p /usr/share/grafana/data

chown -R grafana:grafana /usr/share/grafana
chown -R grafana:grafana /etc/grafana
chmod -R 755 /usr/share/grafana
chmod -R 755 /etc/grafana

